version : '3'
services:
  frontend_yo:
    build: 
      context : .
      dockerfile : Dockerfile.dev
    ports:
      - "7777:3000"
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
  tests:
    build: 
      context : .
      dockerfile : Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command : ["npm","run","test"]
